<!-- -*- mode: html -*- -->
<header>
  <nav>
    <ul id="nav">
      <li> <a href="index.html"> Home</a></li>
      <li> <a href="research.html">Research</a></li>
      <li> <a href="writings.html">Papers</a></li>
      <li> <a href="teaching.html">Teaching</a></li>
      <li> <a href="downloads.html">Software</a></li>
    </ul>
  </nav>
</header>

<script type="text/javascript">highlightCurrentPage()</script>
