<!-- -*- mode: html -*- -->
<header>
  <nav>
    <ul id="nav">
      <li class="left"> <a id="homelink" href="index.html"> Home</a></li>
      <div class="right">
      <li class="left"> <a href="research.html">Research</a></li>
      <li class="left"> <a href="writings.html">Papers</a></li>
      <li class="left"> <a href="teaching.html">Teaching</a></li>
      <li class="left"> <a href="downloads.html">Software</a></li>
      </div>
    </ul>
  </nav>
</header>

<script type="text/javascript">highlightCurrentPage()</script>
