#+TITLE: Massimo Lauria @ Sapienza - Teaching

* Fall 2015 TokyoTech — Introduction to Proof Complexity
   
  “Proof Complexity” is the study of the complexity of proving
  propositional theorems.  In this  course we  discuss various
  proof systems and we will show lower bounds for them.
  
  More information can  be found  at the course [[file:courses/2015.ProofComplexity/][page]].

    
* Spring 2014 KTH — Sum of squares and integer programming relaxations

  The strongest  approximation algorithms in literature  employ linear
  and semidefinite positive relaxations of integer programs.
  
  “Sum of  Squares” is  a simple computation  model that  captures all
  such techniques.   We only know a  handful of lower bounds  for this
  model,  very   few  compared   to  more  established   (but  weaker)
  Lovász-Schrijver and Sherali-Adams hierarchies.
  
  This course will  focus on Sum of Squares: we  will give an overview
  of its relation  with these earlier systems, and we  will see how to
  use  it to  develop better  approximation algorithms.  Then we  will
  study its fundamental limitations, in the form of rank lower bounds.
   
  *TIMEFRAME:* the  course will consist in  *16 lectures*
  of 2  hours each. It  will start in  Week 05 (period  3) and
  will finish in Week 15 (period 4).
  
  More information can  be found  at the course [[http://www.csc.kth.se/~lauria/sos14/][page]].

* Fall 2012 KTH — Communication Complexity (Co-Lecturer)

  This year the course 2D2441 (i.e. “Seminars on Theoretical
  Computer Science”) is  devoted to Communication Complexity and
  is taught by [[http://www.csc.kth.se/~jakobn/][Jakob Nordström]].

  Consider  the following  problem:  Alice  and Bob  want to  compute
  a function $f(x,y)$.  Alice has input $x$ while Bob  has input $y$:
  how  many bit  do they  need to  exchange in  order to  compute the
  desired function?  The study  of such communication  complexity has
  application   in   circuit    design,   data   stream   algorithms,
  cryptography, ecc...
  
  More information can  be found  at the course [[http://www.csc.kth.se/utbildning/kth/kurser/DD2441/semteo12/][page]].
  
* 2010-2011 Uniroma1 — Fondamenti di Programmazione (Esercitazioni)

  Lo scopo delle esercitazioni di questo corso è quello di
  introdurre gli studenti alla programmazione, utilizzando in
  particolare il linguaggio C.  Le peculiarità di questo
  linguaggio permettono agli studenti di acquisire familiarità
  con il concetto di memoria, di puntatore, di gestione degli
  indirizzi ed in generale di concetti che i linguaggi di
  programmazione più moderni tendono a nascondere.
   
  Per maggiori informazioni sul corso consiglio di visitare le seguenti pagine web:
  
  - La [[http://www.dsi.uniroma1.it/~galesi/fond.html][pagina principale]] a cura del [[http://www.dsi.uniroma1.it/~galesi][Prof. Galesi]]
  - Il [[file:courses/2010-Labprog-Uniroma1.html][diario delle esercitazioni]] a cura di Massimo Lauria
     

* 2009-2010 Uniroma1 — Metodi Matematici per L'Informatica (Esercitazioni)

  Nell’anno accademico 2009-2010 ho condotto le esercitazioni
  del Canale P-Z del corso di “Metodi Matematici per
  L’Informatica”. Le informazioni per questo corso non sono su
  questo sito, e possono essere trovate alla seguente pagina
  web:
   
  [[http://twiki.di.uniroma1.it/twiki/view/Logica_PZ/WebHome][Metodi Matematici per L’Informatica (canale P-Z), anno accademico 2009-2010]]

  A grandi linee il corso introduce agli studenti i concetti più
  semplici della logica e del ragionamento deduttivo.  Sia dal
  punto di vista formale, attraverso lo studio dei sistemi
  logici, sia dal punto di vista pratico, mettendoli di fronte
  all’esigenza di capire, riprodurre e <em>produrre</em>
  dimostrazioni matematiche corrette.
   
* 2007-2008 Uniroma1 — Architettura 2 (Tutoraggio) 

  Qui potete trovare il codice sorgente legato alle sessioni di tutoraggio
  per il corso di architettura 2. Se avete domande sul codice potete
  contattarmi o farle durante le sessioni di tutoraggio. Alcuni di questi
  programmi possono essere leggermente diversi da quelli visti in classe.
  Vi prego di segnalare eventuali sviste ed errori nel codice!
  
  *Update:* /Il codice è stato rimosso./

